# Generated by Django 2.2.2 on 2019-09-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20190816_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Estado',
            field=models.CharField(choices=[('', 'Seleccionar estado'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=254),
        ),
    ]
