# Generated by Django 2.2.2 on 2019-09-18 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0008_auto_20190915_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(5, '5 Puntos (Excelente)'), (4, '4 Puntos (Bueno)'), (3, '3 Puntos (Aceptable)'), (2, '2 Puntos (Regular)'), (1, '1 Puntos (Malo)')])),
                ('calificado', models.BooleanField()),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.Producto')),
                ('usuario_calificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
