# Generated by Django 2.2.2 on 2019-09-18 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.CharField(max_length=10, verbose_name='Codigo de Seguimiento')),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado')], default='PREPARACION', max_length=50)),
                ('fecha_en_preparacion', models.DateTimeField(verbose_name='Fecha en preparacion')),
                ('fecha_envio', models.DateTimeField(null=True, verbose_name='Fecha de envio')),
                ('fecha_entregado', models.DateTimeField(null=True, verbose_name='Fecha de entrega')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
