# Generated by Django 2.2.2 on 2019-07-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('Codigo_Seguimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_envio', models.DateTimeField()),
                ('fecha_entregado', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Regalo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_regalo', models.IntegerField()),
                ('Valor_regalo', models.IntegerField()),
                ('imagen', models.FileField(upload_to='Regalo_imagenes/')),
                ('Correo_Para', models.CharField(max_length=50)),
                ('Nombre_De', models.CharField(max_length=50)),
                ('Mensaje', models.CharField(max_length=200)),
                ('Cantidad', models.IntegerField()),
                ('FechaentregaR', models.DateTimeField()),
            ],
        ),
    ]
