# Generated by Django 2.2.2 on 2019-09-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_auto_20190902_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='Fechacompra',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='Valor',
        ),
    ]
