# Generated by Django 2.2.2 on 2019-09-10 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_auto_20190910_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
    ]
