# Generated by Django 2.2.2 on 2019-09-16 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20190915_2159'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compra', '0004_auto_20190910_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizarCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValorTotalPagado', models.PositiveIntegerField()),
                ('Fechacompra', models.DateTimeField(auto_now=True, null=True)),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='itemcarrito',
            old_name='CantidadComprar',
            new_name='Cantidad',
        ),
        migrations.CreateModel(
            name='ItemHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantidadComprada', models.PositiveIntegerField()),
                ('ValorUnitarioPagado', models.PositiveIntegerField()),
                ('Finalizar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.FinalizarCompra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
        ),
    ]
